# Generated by Django 3.2.7 on 2021-10-07 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('mobileNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('empAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('initialLongitude', models.DecimalField(decimal_places=5, max_digits=50)),
                ('initialLatitude', models.DecimalField(decimal_places=5, max_digits=50)),
                ('finalLongitude', models.DecimalField(decimal_places=5, max_digits=50)),
                ('finalLatitude', models.DecimalField(decimal_places=5, max_digits=50)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorkLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currenLatitude', models.DecimalField(decimal_places=5, max_digits=50)),
                ('currenLongitude', models.DecimalField(decimal_places=5, max_digits=50)),
                ('updated_at', models.DateTimeField()),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('workLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.worklocations')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('saveDateTime', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
