# Generated by Django 3.2.7 on 2021-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklocations',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
